name: Upload to Release

on:
  release:
    types:
      - created

jobs:
  upload:
    name: Upload Binaries to Release
    runs-on: ubuntu-latest

    steps:
      # Step 1: Download Artifacts from Previous Workflow
      - name: Download Binaries
        uses: actions/download-artifact@v3
        with:
          name: binaries

      # Step 2: Upload Binaries to Release
      - name: Upload Binaries to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: binaries/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
