name: Build and Upload on new Tag


on:
  release:
    types:
      - created

jobs:
  build-and-upload:
    name: Build and Upload Binaries
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Set up Rust using dtolnay/rust-toolchain
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@nightly
        with:
          targets: x86_64-unknown-linux-gnu

      # Step 3: Build in debug mode
      - name: Build Debug Binary
        run: cargo build --target x86_64-unknown-linux-gnu -p htmeta-cli

      # Step 4: Build in release mode
      - name: Build Release Binary
        run: cargo build --release --target x86_64-unknown-linux-gnu -p htmeta-cli

      # Step 5: Upload the binaries
      - name: Upload Binaries
        run: |
          mkdir artifacts
          cp target/x86_64-unknown-linux-gnu/debug/htmeta binaries/x64-debug-linux-htmeta || true
          cp target/x86_64-unknown-linux-gnu/release/htmeta binaries/x64-release-linux-htmeta || true
        shell: bash

      # Step 2: Upload Binaries to Release
      - name: Upload Binaries to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: binaries/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
